[build]
  base = "/"
  publish = "build/"
  command = "npm run build"

# Do not rewrite /static/* paths
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Handle internal routing for SPAs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
